{{- if and .Values.sumologic.role.create }}
{{- $ctx := . }}
{{- range $namespace := .Values.sumologic.role.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "sumologic.metadata.name.roles.clusterrole" $ctx }}
  namespace: {{ $namespace }}
  labels:
    app: {{ template "sumologic.labels.app.roles.clusterrole" $ctx }}
    {{- include "sumologic.labels.common" $ctx | nindent 4 }}
rules:
- apiGroups: ["", "apps", "extensions", "events.k8s.io"]
  resources:
  - configmaps
  - daemonsets
  - deployments
  - endpoints
  - events
  - namespaces
  - nodes
  - pods
  - replicasets
  - services
  - statefulsets
  verbs: ["get", "list", "watch"]
{{- if eq $namespace $ctx.Release.Namespace}}
- apiGroups: [""]
  resources:
    - configmaps
  verbs: ["create", "patch"]
{{- if $ctx.Values.fluentd.podSecurityPolicy.create }}
- apiGroups: ["policy"]
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ template "sumologic.metadata.name.events.statefulset" $ctx }}
  - {{ template "sumologic.metadata.name.metrics.statefulset" $ctx }}
  - {{ template "sumologic.metadata.name.logs.statefulset" $ctx }}
  verbs: ["use"]
{{- end }}
{{- end }}
{{- end }}
{{- end }}